config/routes.rb
Conch::Application.routes.draw do
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  

  match '/signup',    :to => 'users#new'
  match '/home',    :to => 'pages#home'
  match '/signin',    :to => 'sessions#new'
  match '/signout',    :to => 'sessions#destroy'
  

  root :to => "pages#landing"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  username   :string(255)
#  ref_id     :integer
#  created_at :datetime
#  updated_at :datetime
#

require 'digest'

class User < ActiveRecord::Base
  
  attr_accessor :password
  attr_accessible :name, :email, :username, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true, :length => { :maximum => 30 }
  
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
  
  validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
  
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..20 }
                       
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password.
    def has_password?(submitted_password)
      encrypted_password == encrypt(submitted_password)
    end
    
    def self.authenticate(email, submitted_password)
        user = find_by_email(email)
        return nil  if user.nil?
        return user if user.has_password?(submitted_password)
      end

      def self.authenticate_with_salt(id, cookie_salt)
        user = find_by_id(id)
        (user && user.salt == cookie_salt) ? user : nil
      end
  
  private

    def encrypt_password
          self.salt = make_salt unless has_password?(password)
          self.encrypted_password = encrypt(password)
        end

        def encrypt(string)
          secure_hash("#{salt}--#{string}")
        end

        def make_salt
          secure_hash("#{Time.now.utc}--#{password}")
        end

        def secure_hash(string)
          Digest::SHA2.hexdigest(string)
        end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title='Hello Conchito home'
  end

  def landing
    @title='Hello Conchito landing'
  end
  
  def about
    @title='Hello Conchito about'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @title = "Sign In"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                               params[:session][:password])
      if user.nil?
        flash.now[:error] = "We're sorry, invalid email/password combination."
              @title = "Sign in"
              render 'new'
      else
        sign_in user
        redirect_to root_path
      end
  end
  
  def destroy
      sign_out
      redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
      @user = User.find(params[:all])
      @title = 'Users'
  end
  
  def show
      @user = User.find(params[:id])
      @title = @user.name
  end
    
  def new
    @user = User.new
    @title = 'Sign Up'
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Thank you for signing up!"
      redirect_to @user
    else
      @title = 'Sign Up'
      render 'new'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
      cookies.permanent.signed[:remember_token] = [user.id, user.salt]
      self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
      !current_user.nil?
  end
  
  def sign_out
      cookies.delete(:remember_token)
      self.current_user = nil
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 80 })
      gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                              :class => 'gravatar',
                                              :gravatar => options)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= csrf_meta_tag %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->    
  <%= stylesheet_link_tag 'style' %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,600,300' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%#= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body>
		
	<div id='right_bar'></div>
	
	<div id='header'>
		<div id='inner'>
		<% if signed_in? %>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
			
			<div class="text"><span class='normal'>Haven’t joined us yet? </span><span class='red'><%= link_to 'Register here', signup_path %></span></div>
			<div class='login'>
			<%= form_for(:session, :url => sessions_path, :class=>'login') do |f| %>
			  <div class="field">
			    <%= f.label :email, 'Email' %>
			  </div>
			  <div class='inputs'><%= f.text_field :email %></div>
			  <div class="field">
			    <%= f.label :password, 'Password' %>
			  </div>
			  <div class='inputs'><%= f.password_field :password %></div>
			  <div class="btn">
			    <%= f.submit "" %>
			  </div>
			<% end %>
			</div>
		<% end %>
				
			</div>
		</div>
	</div>
	
	<div id='cont'>
		  <%= yield %>
	</div>
	
	<div id='footer'></div>
	
	
	<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Sample App</h1>

<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to "Sign up now!", '#', :class => "signup_button round" %>

app/views/pages/index.haml
Hablame

app/views/pages/landing.html.erb
<div class='info'>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/signup.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/shared/_error_messages.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>

app/views/users/new.html.erb
<div id='signup'>

<%= render 'shared/error_messages' %>

<h1>Sign up</h1>
<h2>*All fields must be completed</h2>

<div class='form'>
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :ref_id, 'Referral Code' %>
    <%= f.text_field :ref_id %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
	<div class='btn'>
    	<%= f.submit "" %>
	</div>
  </div>
<% end %>
</div>

<h3>By clicking the register button, you are automatically accepting feteeze.com's terms and conditions.</h3>


</div>

app/views/users/show.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1><%= gravatar_for @user %></h1>
	  <h1 style='color:#000'><%= @user.name %></h1>
    </td>
    <td class="sidebar round"  style='color:#000'>
      <strong>Name:</strong> <%= @user.name %><br />
      <strong>URL:</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>